version: "3.3"
# services:
#   web:
#     build: ./web/
#     command: python manage.py run -h 0.0.0.0
#     volumes:
#       - ./web/:/usr/src/app/
#     ports:
#       - 8000:8000
#     env_file:
#       - ./.env.dev
services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile.web
    container_name: web_app
    volumes:
      - ./web/:/app
    ports:
      - 8000:8000
  db:
    image: postgres:15.2-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data/
        - ./postgres/stamp_db.sql:/docker-entrypoint-initdb.d/stamp_db.sql
        # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amph_stamp_db
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/amph_stamp_db
    ports:
      - '54321:5432'
    container_name: postgres

volumes:
  postgres_data:
    driver: local