FROM ubuntu:focal
# FROM python:3.10.7-slim-buster
# команда ран - на фазе сборки
RUN apt update
RUN apt install -y python3-pip
RUN pip3 install Flask-SQLAlchemy
# RUN pip3 install eve-sqlalchemy


# создать дирректорию
RUN mkdir -p /app
# указать дирректорию в которой мы будем выполнять наше приложение
WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt


# копируем все[если . /app/] содержимое из текущей дирриктории в папку /app , можно указать конкретную папку
COPY . /app/

# команда для запуска на этапе выполнения контейнера
CMD ["python3", "init_web.py"]
# CMD ["python3", "init_db.py"]

# порт который мы хотим отдавать
EXPOSE 8000
